### PR TITLE
Fixes and CI

### PR DESCRIPTION
**Pull request by seriema**
Me and a friend really liked your project and we're using it. It has some compiler warnings that are a bit annoying, so I fixed them and added a few things. If you're unfamiliar with CI services like [Travis](https://travis-ci.com/) and [AppVeyor](http://www.appveyor.com/) they're build servers that will build your project for every pushed commit. It's especially useful for open source projects on Github as they'll build (and test, if set up) all Pull Requests so you know that you contributions aren't breaking the project (hopefully hehe).

You'll need to:
- sign up with Travis and AppVeyor (they're free) and turn on the builds for your project
- update the URL in the README.md badge from AppVeyor

### CODE REVIEW

**Comment by seriema** [comment]
@Chlumsky *poke*

**Comment by Chlumsky** [comment]
Hello, I prefer to keep things simple, so I'm not going to add the "CI services" thingies right now, but I agree with your other points.

**Comment by seriema** [comment]
I see you already cherry picked some of the commits. Great! Would you consider the `.gitignore` one as well? Visual Studio craps all over ones git working directory otherwise.

I'd like to defend the choice of having those CI's set up now to make sure any commits you or any PR adds compiles on all three platforms because nothing's more annoying as a library user (me in this case) than a library failing on my platform because the library author usually just checks on their own machine. But I'm unsure how much experience you have with them. If you have used them a lot and really don't want it now then it's ok. If you haven't used them before and it just seems iffy then I'd like to show how you don't need to do anything and how great they are to have in an open source project (especially on Github).

**Comment by ccbrown** [comment]
> I prefer to keep things simple, so I'm not going to add the "CI services" thingies right now

Automated tests are a cornerstone of any quality software project. It's a universally good idea.

To add to that, unit tests are generally considered a pretty good idea as well. I guarantee that if you wrote some, you'd find new bugs and end up with a much more stable project as a result.

**Pull request closed without merging**
