### PR TITLE
Implement C-API & FreeType runtime loader to allow other languages to interop with the library

### PR DESCRIPTION
**Pull request by KitsuneAlex**
As the title suggests, i went ahead and implemented a C-API wrapper for msdfgen-core and the FreeType extensions.
Originally this wrapper was supposed to be a part of my upcoming LWJGL PR for adding msdfgen bindings,
but i thought the project itself could maybe use it even better :)

**UPDATE:** Another thing i implemented out of personnal necessity is a runtime loader for FreeType which doesn't require linking msdfgen against it statically and offers an API to set a custom function load callback.

Also adds a reasonable default configuration for clang-format ~~and clang-tidy~~, so IDEs like CLion don't permanently mess up the code formatting.

I am open for any improvement suggestions or nitpicks. Cheers.

### CODE REVIEW

**Comment by Type1J** [comment]
I haven't looked it the code, but a C API would be nice.

**Comment by zmarlon** [comment]
Looks good!

**Comment by DietrichPaul** [comment]
We have been looking for a C API fork for a long time, implementation would be great. The code is clean.

**Comment by lunarydess** [comment]
Looks clean :)

**Comment by KitsuneAlex** [comment]
There is a rough, but [working implementation draft](https://github.com/LWJGL/lwjgl3/pull/977) for LWJGL now.

**Comment by KitsuneAlex** [comment]
I think i'm quite happy with how this looks now @Chlumsky :)

**Comment by KitsuneAlex** [comment]
Not sure about the header/source files names tbh, i think you might prefer `msdfgen-c` over `msdfgen_c` judging by your other files 😄

**Comment by KitsuneAlex** [comment]
Messed up title of the last commit but you might wanna squah anyways if you want to merge.

**Comment by KitsuneAlex** [comment]
Gonna leave this as-is for now until you have time to take a look. But i found another inconsistency in my API draft i might wanna address.

**Comment by KitsuneAlex** [comment]
I removed the allocator API for now as it would require a larger refactor to implement properly throughout the codeebasee. I also added support for the FreeType font import API with a fitting `msdfgen-ext-c.h` :)

**Comment by KitsuneAlex** [comment]
Tested implementation in LWJGL using a custom runtime loader. Works like a charm.

**Comment by Chlumsky** [comment]
Sorry, but if I merged this, I would have to support it for eternity, even though I don't use it, so I think it will be better if you keep it updated in your own fork.

**Pull request closed without merging**
