### PR TITLE
Add a flag that uses nanosvg.

### PR DESCRIPTION
**Pull request by fire**
Support more svg files.

### CODE REVIEW

**Comment by fire** [comment]
In my file the svg generates 5 shapes. To support that, a min operation needs to be done on the 5 outputs.

**Comment by fire** [comment]
I expect all the colored shapes to be white. How can I do that?

out
[index.zip](https://github.com/Chlumsky/msdfgen/files/4177223/index.zip)

**Comment by Chlumsky** [comment]
So this adds a dependency that is larger than the project itself and all it improves is that it finds more than one shape in the SVG, which can be easily added to the original implementation as well, except for the fact that finding the paths is not the problem, combining them is, and obviously, this "upgrade" doesn't do anything about that. I'm not even going to comment on how it turns everything, even straight lines into cubic curves.

**Comment by fire** [comment]
Thank you for the comments, I was unable to get multiple shapes working with your implementation, it should be possible. I noticed your documentation says it takes the last shape.

My plan was to stack the sdfs and color the sdfs to output color emoji, but all of this is expensive in the number of textures. Did you have an approach for this? The shapes winding order fails when overlapping. I can provide svgs.

I noticed there are corner cases when I can generate a line that fills horizontally the entire sdf.

I’m blocked on these two issues, which is why I tried this approach. Please advise.

**Comment by Chlumsky** [comment]
The problem is that the algorithm requires strictly non-intersecting shapes to work properly, and with consistent winding direction. So if you want to use an SVG that has multiple overlapping paths, the only way would be to preprocess the path using something like [Paper.js](http://paperjs.org/examples/boolean-operations/) and then pass it to msdfgen.

When it comes to color emojis, you would always need to generate an SDF for each color, since the SDF only represents a colorless shape.

Please post the case where a line fills horiznontally the entire sdf, that might be a bug.

**Pull request closed without merging**
